# Generated by Django 4.0 on 2022-01-03 19:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_question_description_question_question_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 3, 19, 53, 29, 526451)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AddField(
            model_name='solution',
            name='solution',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userprofile'),
        ),
    ]
