# Generated by Django 4.0.1 on 2022-01-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_email_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatedQuestion',
        ),
    ]
