# Generated by Django 4.0.1 on 2022-01-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_questiontag_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_tags',
        ),
    ]
