# Generated by Django 4.0.1 on 2022-01-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_question_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag_entries',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
