# Generated by Django 4.0.1 on 2022-01-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_question_question_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tag_entries',
            new_name='tag_names',
        ),
    ]
