# Generated by Django 4.0.1 on 2022-01-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_tag_entries_question_tag_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AlterField(
            model_name='question',
            name='tag_names',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='QuestionTag',
        ),
    ]
