# Generated by Django 4.0.1 on 2022-01-29 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_solution_question_alter_solution_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
    ]
