# Generated by Django 4.0.1 on 2022-01-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_solution_question_alter_solution_solution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedquestion',
            old_name='user',
            new_name='user_profile',
        ),
    ]
