# Generated by Django 4.0.1 on 2022-03-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_attemptedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptedquestion',
            name='num_times_attempted',
            field=models.IntegerField(default=1),
        ),
    ]
