# Generated by Django 3.2.9 on 2022-07-11 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_attemptedquestion_num_times_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='api.question'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='api.userprofile'),
        ),
    ]
