# Generated by Django 3.2.9 on 2022-07-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20220711_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='user_profile',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='question',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to='api.userprofile'),
        ),
    ]
