# Generated by Django 3.1.4 on 2022-07-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_question_creator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solution',
            new_name='SolutionAttempt',
        ),
    ]
