# Generated by Django 3.1.4 on 2022-07-16 06:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20220716_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='/default_profile_pic.png', upload_to=api.models.user_profile_pic_directory),
        ),
    ]
