# Generated by Django 3.1.4 on 2022-07-16 10:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_title',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default='easy', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='exam_board',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='question',
            name='exam_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='num_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='official_solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, upload_to=api.models.question_img_directory),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='solutionattempt',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solutionattempt',
            name='solution_img',
            field=models.ImageField(blank=True, upload_to=api.models.solution_img_directory),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='/profile_pics/default_profile_pic.png', upload_to=api.models.user_profile_pic_directory),
        ),
    ]
