# Generated by Django 3.1.4 on 2022-07-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20220716_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttemptedQuestion',
        ),
    ]
