# Generated by Django 3.1.4 on 2022-07-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_question_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple_choices',
            field=models.TextField(blank=True),
        ),
    ]
