# Generated by Django 4.0.1 on 2022-08-03 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_question_multiple_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimage',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_images', to='api.question'),
        ),
    ]
