# Generated by Django 4.0.1 on 2022-08-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_questionimage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_images',
            field=models.BooleanField(default=False),
        ),
    ]
