# Generated by Django 4.1 on 2022-08-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20220805_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionattempt',
            name='session_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='SolutionImage',
        ),
    ]
