# Generated by Django 4.1 on 2022-08-15 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_userquestionsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionsession',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sessions', to='api.userprofile'),
        ),
    ]
