# Generated by Django 4.1 on 2022-08-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_userquestionsession_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionattempt',
            name='session_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userquestionsession',
            name='session_id',
            field=models.TextField(null=True),
        ),
    ]
