# Generated by Django 4.1 on 2022-08-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_solutionattempt_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionattempt',
            name='question_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userquestionsession',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
