# Generated by Django 4.1 on 2022-10-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_solutionattempt_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.TextField(blank=True),
        ),
    ]
