# Generated by Django 4.1 on 2022-08-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_solutionattempt_question_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionsession',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='userquestionsession',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
