# Generated by Django 4.1 on 2022-10-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.TextField(null=True),
        ),
    ]
