# Generated by Django 4.1 on 2022-08-18 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_userquestionsession_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninsession',
            name='username',
        ),
        migrations.RemoveField(
            model_name='userquestionsession',
            name='username',
        ),
        migrations.AddField(
            model_name='questioninsession',
            name='user_profile_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquestionsession',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_sessions', to='api.userprofile'),
            preserve_default=False,
        ),
    ]
