# Generated by Django 4.1 on 2022-10-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
