# Generated by Django 4.1 on 2022-08-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_userquestionsession_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionattempt',
            name='creator',
        ),
        migrations.AddField(
            model_name='solutionattempt',
            name='username',
            field=models.TextField(default='VladF'),
            preserve_default=False,
        ),
    ]
