# Generated by Django 4.0.1 on 2022-12-12 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_solutionattempt_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninsession',
            name='username',
        ),
        migrations.RemoveField(
            model_name='solutionattempt',
            name='username',
        ),
        migrations.RemoveField(
            model_name='userquestionsession',
            name='username',
        ),
        migrations.AddField(
            model_name='questioninsession',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions_in_session', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='solutionattempt',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='userquestionsession',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question_sessions', to='api.userprofile'),
        ),
    ]
