# Generated by Django 3.1.4 on 2022-08-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20220819_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='creator',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='savedquestion',
            old_name='user_profile',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='solutionattempt',
            old_name='creator',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='userquestionsession',
            old_name='user_profile',
            new_name='profile_id',
        ),
    ]
