# Generated by Django 4.0.1 on 2022-12-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_questioninsession_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioninsession',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_in_session', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='solutionattempt',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='userquestionsession',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sessions', to='api.userprofile'),
        ),
    ]
