# Generated by Django 3.1.4 on 2022-08-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20220819_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='profile_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='savedquestion',
            old_name='profile_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='solutionattempt',
            old_name='profile_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='userquestionsession',
            old_name='profile_id',
            new_name='user_id',
        ),
    ]
