# Generated by Django 4.0.1 on 2022-12-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_questioninsession_user_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='creator',
            new_name='user_profile',
        ),
    ]
