# Generated by Django 4.0.1 on 2022-12-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_userprofile_rank_questionfilterresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
