# Generated by Django 4.0.1 on 2022-12-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_userprofile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionimage',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_images', to='api.userprofile'),
            preserve_default=False,
        ),
    ]
