# Generated by Django 4.0.1 on 2023-05-13 13:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_questionimage_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.ImageField(default='profile_pics/default_profile_pic.png', upload_to=api.models.user_profile_pic_directory),
        ),
    ]
